POST {{basePath}}/api/scorestack/template
kbn-xsrf: true
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Wordpress - Twenty Twenty",
  "description": "Checks the content of the default homepage for Wordpress's Twenty Twenty theme.",
  "protocol": "HTTP",
  "score_weight": 1,
  "definition": {
    "method": "GET",
    "route": "/index.html"
  }
}

###

PUT {{basePath}}/api/scorestack/template/12345
kbn-xsrf: true
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Website DNS",
  "description": "Checks the value of the A record for the company website.",
  "protocol": "DNS",
  "score_weight": 1,
  "definition": {
    "record": "www",
    "value": "127.0.0.1"
  }
}

###

POST {{basePath}}/api/scorestack/template
kbn-xsrf: true
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "title": "Invalid Check",
  "description": "This request should fail, because the protocol is invalid.",
  "protocol": "asdfasdf",
  "score_weight": 1,
  "definition": {
    "key": "value"
  }
}

###

GET {{basePath}}/api/scorestack/template/12345
kbn-xsrf: true
Authorization: Basic {{username}}:{{password}}

###

GET {{basePath}}/api/scorestack/template
kbn-xsrf: true
Authorization: Basic {{username}}:{{password}}